coffeshop/urls.py
from django.contrib import admin
from django.urls import path
from users import views as users_views
from blogs import views as blogs_views
from shop import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('blog/<slug:slug>',blogs_views.blog,name="blog"),
    path('blogs/',blogs_views.blogs,name="blogs"),
    path('register/',users_views.register,name="register"),
    path('login/',users_views.loginuser,name="login"),
    path('delete/<int:id>',views.deletecoffeincart,name="deletecoffeincart"),
    path('updateuser/',users_views.updateuser,name="updateuser"),
    path('logoutuser/',users_views.logoutuser,name="logoutuser"),
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('order/',views.order,name="order"),
    path('coffes/',views.coffes,name="coffes"),
    path('<slug:slug>/',views.coffesdetail,name="coffesdetail"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

def create_superuser():
    from django.contrib.auth import get_user_model
    User = get_user_model()
    if not User.objects.filter(email="admin").exists():
        User.objects.create_superuser(
            first_name = "Mustafa Kayra",
            last_name = "Toker",
            email="m.toker2009@gmail.com",
            password="adminpassword123"
        )

try:
    create_superuser()
except Exception as e:
    print(f"Superuser creation error: {e}")

blogs/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings

class Commentreply(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,verbose_name="Yorum Yanıt Yazarı")
    content = models.TextField(null=False,blank=False,verbose_name="Yorum Yanıt İçeriği")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")

    class Meta:
        verbose_name = "Yorum Yanıtı"
        verbose_name_plural = "Yorum Yanıtları"

    def __str__(self):
        return f"{self.content}"



class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=False,blank=False,verbose_name="Yorum Yazarı")
    content = models.TextField(null=False,blank=False,verbose_name="Yorum İçeriği")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    reply = models.ManyToManyField(Commentreply,null=True,blank=True,verbose_name="Yorum Yanıtları")

    class Meta:
        verbose_name = "Yorum"
        verbose_name_plural = "Yorumlar"

    def __str__(self):
        return f"{self.content}"
    


class Content(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True,verbose_name="Başlık(İsteğe Göre Yazılabilir)")
    content = models.TextField(null=False,blank=False,verbose_name="İçerik")

    class Meta:
        verbose_name = "İçerik"
        verbose_name_plural = "İçerikler"

    def __str__(self):
        return f"{self.name}"



class Blog(models.Model):
    name = models.CharField(max_length=100,null=False,blank=False,verbose_name="Blog İsmi")
    description = models.CharField(max_length=1000,null=False,blank=False,verbose_name="Açıklama")
    image = models.ImageField(upload_to="blogimages/",null=False,blank=False,verbose_name="Blog Kapak Resmi")
    content = models.ManyToManyField(Content,null=False,blank=False,verbose_name="İçerikler")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    slug = models.SlugField(null=False,blank=True,unique=True,db_index=True,verbose_name="URL")
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=True,verbose_name="Yazar")
    comments = models.ManyToManyField(Comment,null=True,blank=True,verbose_name="Yorumlar")

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Bloglar"

    def save(self, *args, **kwargs): #This function adds slug by title
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return f"{self.name}"
    


class Contact(models.Model):
    name = models.CharField(max_length=50,null=False,blank=False,verbose_name="İsim")
    email = models.EmailField(null=False,blank=False,verbose_name="Email")
    subject = models.CharField(max_length=500,null=False,blank=False,verbose_name="Konu")
    message = models.TextField(null=False,blank=False,verbose_name="Mesaj")

    class Meta:
        verbose_name = "İletişim Formu"
        verbose_name_plural = "İletişim Formları"

    def __str__(self):
        return f"{self.name} | {self.subject}"

shop/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings

class Optionels(models.Model):
    name = models.CharField(max_length=100,null=False,blank=False,verbose_name="Opsiyon İsmi")

    class Meta:
        verbose_name = "Opsiyon Kategorisi"
        verbose_name_plural = "Opsiyon Kategorileri"

    def __str__(self):
        return f"{self.name}"


class Option(models.Model):
    optionels = models.ForeignKey(Optionels,null=False,blank=False,verbose_name="Opsiyon Kategorisi",on_delete=models.CASCADE)
    name = models.CharField(max_length=200,null=False,blank=False,verbose_name="Opsiyon İsmi")

    class Meta:
        verbose_name = "Opsiyon"
        verbose_name_plural = "Opsiyonlar"

    def __str__(self):
        return f"{self.optionels} | {self.name}"


class Images(models.Model):
    name = models.CharField(max_length=200,null=False,blank=False,verbose_name="İçecek İsmi")
    image = models.ImageField(upload_to="coffeimages/",verbose_name="İçecek Resimleri")

    class Meta:
        verbose_name = "İçecek Resmi"
        verbose_name_plural = "İçecek Resimleri"

    def __str__(self):
        return f"{self.name}"


class Item(models.Model):
    name = models.CharField(max_length=100,null=False,blank=False,verbose_name="İçecek İsmi")
    description = models.TextField(null=False,blank=False,verbose_name="İçecek Açıklaması")
    image = models.ForeignKey(Images,null=False,blank=True,verbose_name="İçecek Resimleri",on_delete=models.CASCADE)
    optionels = models.ManyToManyField(Optionels,null=False,blank=False)
    price = models.FloatField(null=False,blank=True,verbose_name="Fiyat")
    slug = models.SlugField(null=False,blank=True,unique=True,db_index=True,verbose_name="URL")
    numberofsales = models.IntegerField(null=False,blank=True,default=0,verbose_name="Satış Sayısı")

    class Meta:
        verbose_name = "İçecek"
        verbose_name_plural = "İçecekler"

    def save(self, *args, **kwargs): #This function adds slug by title
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return f"{self.name}"
    

class OrderItem(models.Model):
    item = models.ForeignKey(Item,null=False,blank=False,on_delete=models.CASCADE,verbose_name="Sipariş Edilen İçecek")
    piece = models.IntegerField(null=False,blank=False,default=1,verbose_name="İçecek Sayısı")
    options = models.ManyToManyField(Option,null=True,blank=True,verbose_name="Opsiyonlar")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")

    class Meta:
        verbose_name = "Sipariş Edilen İçecek"
        verbose_name_plural = "Sipariş Edilen İçecekler"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


    def __str__(self):
        options_str = ", ".join(option.name for option in self.options.all())
        return f"{self.item} | {options_str} | {self.piece}"

    
    def totalprice(self):
        total = self.piece * self.item.price
        return total
    
    def numberofsalespiece(self):
        salespiece = self.piece + self.item.numberofsales
        return salespiece

    
class ShoppingCart(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL,null=False,blank=False,on_delete=models.CASCADE,verbose_name="Müşteri")
    orderitems = models.ManyToManyField(OrderItem,null=False,blank=False,verbose_name="Sipariş Edilen İçecekler")
    date_created = models.DateTimeField(auto_now_add=True,verbose_name="Sepetin Oluşturulma Tarihi")
    ordered = models.BooleanField(default=False,blank=False,null=False,verbose_name="Sipariş Edilme Durumu")

    class Meta:
        verbose_name = "Sepet"
        verbose_name_plural = "Sepetler"

    def __str__(self):
        return f"{self.customer} Siparişi"
    
    def totalpricecart(self):
        return sum(order_item.totalprice() for order_item in self.orderitems.all())
    
    def totalnumberofsalespiece(self):
        return sum(order_item.numberofsalespiece() for order_item in self.orderitems.all())
    

class OrderedCard(models.Model):
    shoppingcart = models.ForeignKey(ShoppingCart,null=False,blank=False,on_delete=models.CASCADE,verbose_name="Sepet")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Sipariş Edilme Tarihi")
    complete = models.BooleanField(default=False,blank=False,null=False,verbose_name="Tamamlanma Durumu")

    class Meta:
        verbose_name = "Sipariş"
        verbose_name_plural = "Siparişler"

    def __str__(self):
        return f"{self.shoppingcart} | {self.date}"

blogs/forms.py
from django import forms
from .models import Contact

class Contactform(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name','email','subject','message']

blogs/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
from shop.models import Item

def blog(request,slug):
    footercoffes = Item.objects.order_by('-numberofsales')[:4]
    blog = get_object_or_404(Blog,slug=slug)
    context = {
        "blog":blog,
        "footercoffes":footercoffes
    }
    return render(request,"blog.html",context)


def blogs(request):
    blog = Blog.objects.all()
    footercoffes = Item.objects.order_by('-numberofsales')[:4]
    context = {
        "blog":blog,
        "footercoffes":footercoffes
    }
    return render(request,"blogs.html",context)

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>{{ coffe.name }}</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">   
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <body>
      <!--header section start -->
      <div class="header_section">
         <div class="container-fluid">
         {% if request.user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <div class="logo"><a href="{% url 'index' %}"><h1 class="navbar-h1">Grande Coffe</h1></a></div>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="/">Anasayfa</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}#contact">İletişim</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'coffes' %}">Kahveler</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'order' %}">Sepet</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs' %}">Bloglar</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'updateuser' %}">Kullanıcı Bilgileri</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'logoutuser' %}">Çıkış Yap</a>
                     </li>
                  </ul>
               </div>
            </nav>
         {% else %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <div class="logo"><a href="{% url 'index' %}"><h1 class="navbar-h1">Grande Coffe</h1></a></div>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Anasayfa</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}#contact">İletişim</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'coffes' %}">Kahveler</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs' %}">Bloglar</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Kayıt Ol</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Giriş Yap</a>
                     </li>
                  </ul>
               </div>
            </nav>
         {% endif %}
         </div>
      </div>
      <!--header section end -->
      <!-- about section start -->
      <div class="about_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-6">
                  <div class="about_taital_main">
                     {% if messages %}
                
                        {% for message in messages %}
                        {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                        {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                        {% endif %}


                        {% endfor %}
                     
                     {% endif %}
                     <div class="coffedetail_taital">{{ coffe.name }}</div>
                     <p class="coffedetail_text">{{ coffe.description }}</p>
                     <div class="coffe-price"><a href="">{{ coffe.price }} TL</a></div>
                     <form method="post">
                     {% csrf_token %}
                     <div class="option_group">
                        {% for optionel in coffe.optionels.all %}
                           <p class="optionel_name">{{ optionel.name }}</p>
                           <div class="btn-group btn-group-toggle option_choices" data-toggle="buttons">
                              {% for option in optionel.option_set.all %}
                                 <label class="btn btn-outline-primary">
                                    <input type="checkbox" name="options" value="{{ option.id }}">
                                    {{ option.name }}
                                 </label>
                              {% endfor %}
                           </div>
                        {% endfor %}
                     </div>
                     <div class="piece_group">
                        <p class="piece_name">Kahve Sayısı</p>
                        <select class="custom-select my-1 mr-sm-2 piece_choice" id="inlineFormCustomSelectPref" name="piece">
                           <option value="1" selected>1</option>
                           <option value="2">2</option>
                           <option value="3">3</option>
                           <option value="4">4</option>
                        </select>
                     </div>
                     <button type="submit" class="btn btn-success button_about">Sipariş Ver</button>
                     </form>
                  </div>
               </div>
               <div class="col-md-6 coffe_image_group">
                  <img src="{{ coffe.image.image.url }}" alt="{{ coffe.image }}" class="coffe-image">                
               </div>
            </div>
         </div>
      </div>
      <!-- about section end -->
      <!-- footer section start -->
      <div class="footer_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-3 col-sm-6">
                  <h3 class="useful_text">Hakkımızda</h3>
                  <p class="footer_text">Grande Coffee olarak, dünyanın dört bir yanından en kaliteli kahve çekirdeklerini özenle seçiyor, her yudumda unutulmaz bir deneyim sunuyoruz. Kahve sanatını tutkuyla icra ediyor, sizlere huzurlu bir ortamda eşsiz lezzetler vaat ediyoruz.</p>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <h3 class="useful_text">Menü</h3>
                  <div class="footer_menu">
                     <ul>
                        <li><a href="/">Anasayfa</a></li>
                        <li><a href="{% url 'coffes' %}">Kahveler</a></li>
                        <li><a href="">Bloglar</a></li>
                        <li><a href="{% url 'register' %}">Kayıt Ol</a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <h3 class="useful_text">Linkler</h3>
                  <div class="footer_menu">
                     <ul>
                     {% for footercoffe in footercoffes %}
                        <li><a href="{% url 'coffesdetail' footercoffe.slug %}">{{ footercoffe.name }}</a></li>
                     {% endfor %}
                     </ul>
                  </div>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <h1 class="useful_text">İletişim</h1>
                  <div class="location_text">
                     <ul>
                        <li>
                           <a href="#">
                           <i class="fa fa-map-marker" aria-hidden="true"></i><span class="padding_left_10">Address : Loram Ipusm</span>
                           </a>
                        </li>
                        <li>
                           <a href="#">
                           <i class="fa fa-phone" aria-hidden="true"></i><span class="padding_left_10">Call : +01 1234567890</span>
                           </a>
                        </li>
                        <li>
                           <a href="#">
                           <i class="fa fa-envelope" aria-hidden="true"></i><span class="padding_left_10">Email : m.toker2009@gmail.com</span>
                           </a>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text"><a href="https://www.linkedin.com/in/mustafa-kayra-toker-b89247283/">Mustafa Kayra Toker</a> tarafından geliştirildi</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'js/navbar.js' %}"></script>
   </body>
</html>